# Generated by Django 3.1.2 on 2021-01-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201223_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='skill',
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.ManyToManyField(related_name='get_skills', to='core.Skill', verbose_name='Categorias'),
        ),
    ]
