# Generated by Django 3.1.2 on 2021-01-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210104_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.ManyToManyField(related_name='get_skills', to='core.About', verbose_name='Skills'),
        ),
    ]
