# Generated by Django 3.1.2 on 2021-01-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210104_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.ManyToManyField(related_name='get_abouts', to='core.Skill', verbose_name='Skills'),
        ),
    ]
